Make `configure`, `make` more compatible to other packages
- new option `--with-gaproot` for configure
- old `make clean` is now `make cleanlast`
- new `make clean` does not remove `Makefile`

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,17 +1,21 @@
 #!/bin/sh
 # (C) Frank Lübeck     2018
-# configure script for EDIM with GAP > 4.8 (different build system for GAP)
+# configure script for EDIM with GAP > 4.11 (different build system for GAP)
 
 # some tools on OS X made locale related problems, so:
 export LANG=C
 export LC_ALL=C
 
 # GAP path
-if [ $# = 0 ]; then
-  GAPPATH="../../"
-else
-  GAPPATH=$1
-fi
+GAPPATH=../..
+while test "$#" -ge 1 ; do
+  option="$1" ; shift
+  case "$option" in
+    --with-gaproot=*) GAPPATH=${option#--with-gaproot=}; ;;
+    -*)               echo "ERROR: unsupported argument $option" ; exit 1;;
+    *)                GAPPATH="$option" ;;
+  esac
+done
 echo "Using $GAPPATH as GAP build directory."
 
 if [ -e "$GAPPATH/sysinfo.in" ]; then
